# Generated by Django 2.0.3 on 2018-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx0026_app001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
