# Generated by Django 2.0.3 on 2018-03-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xx0026_app001', '0002_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='xtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xx0026_app001.Topic'),
            preserve_default=False,
        ),
    ]
